#! /bin/bash

echo "Ajout de l'utilisateur equinox-loader"
adduser --system equinox-loader --no-create-home --disabled-login
addgroup --system equinox-loader

echo "creation repertoire /var/log/equinox-loader"
mkdir -p /var/log/equinox-loader

echo "Changement des droits sur le repertoire /opt/equinox-loader"
chown -R equinox-loader:equinox-loader /opt/equinox-loader

chmod go-rwx /opt/equinox-loader -R
chmod u+rwx /opt/equinox-loader -R
chmod go+rx /opt/equinox-loader -R


echo "Changement des droits sur le repertoire /var/log/equinox-loader"
chown -R equinox-loader:equinox-loader /var/log/equinox-loader

chmod go-rwx /var/log/equinox-loader -R
chmod u+rwx /var/log/equinox-loader -R
chmod go+rx /var/log/equinox-loader -R




#echo "Enregistrement du service equinox-loader"  
#update-rc.d equinox-loader default


