//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.08 at 11:05:57 PM CET
//

package org.tc.osgi.bundle.requirement.tracking.core.graph;

import java.util.HashSet;

import javax.xml.bind.annotation.XmlRegistry;

import org.tc.osgi.bundle.requirement.tracking.core.graph.m2.node.DescriptionNode;
import org.tc.osgi.bundle.requirement.tracking.core.graph.m2.node.RequirementNode;
import org.tc.osgi.bundle.requirement.tracking.core.graph.m2.node.VersionNode;
import org.tc.osgi.bundle.requirement.tracking.core.graph.m2.relation.BasicRelation;
import org.tc.osgi.bundle.requirement.tracking.core.graph.m2.relation.DependencyRelation;
import org.tc.osgi.bundle.requirement.tracking.core.graph.m2.relation.TrackingRelation;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.tc.osgi.bundle.requirement.tracking.core.graph package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.tc.osgi.bundle.requirement.tracking.core.graph
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BasicRelation }
     *
     */
    public BasicRelation createBasicRelation() {
        return new BasicRelation();
    }

    /**
     * Create an instance of {@link DependencyRelation }
     *
     */
    public DependencyRelation createDependencyRelation() {
        return new DependencyRelation();
    }

    /**
     * Create an instance of {@link DescriptionNode }
     *
     */
    public DescriptionNode createDescriptionNode() {
        return new DescriptionNode();
    }

    /**
     * Create an instance of {@link HashSet }
     *
     */
    public HashSet createHashSet() {
        return new HashSet();
    }

    /**
     * Create an instance of {@link NodeSet }
     *
     */
    public NodeSet createNodeSet() {
        return new NodeSet();
    }

    /**
     * Create an instance of {@link RelationSet }
     *
     */
    public RelationSet createRelationSet() {
        return new RelationSet();
    }

    /**
     * Create an instance of {@link RequirementNode }
     *
     */
    public RequirementNode createRequirementNode() {
        return new RequirementNode();
    }

    /**
     * Create an instance of {@link TrackingGraph }
     *
     */
    public TrackingGraph createTrackingGraph() {
        return new TrackingGraph();
    }

    /**
     * Create an instance of {@link TrackingRelation }
     *
     */
    public TrackingRelation createTrackingRelation() {
        return new TrackingRelation();
    }

    /**
     * Create an instance of {@link VersionNode }
     *
     */
    public VersionNode createVersionNode() {
        return new VersionNode();
    }

}
